# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodieBagFrontend' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoodieBagFrontend
pod 'Flurry-iOS-SDK/FlurrySDK'

  target 'FoodieBagFrontendTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FoodieBagFrontendUITests' do
    # Pods for testing
  end


end
